"""Recipe corpus for Pantry to Plan.

40 lunch/dinner recipes, 10 per cuisine (italian, american, chinese, indian),
with at least 5 vegetarian recipes per cuisine so a 3-5 day all-vegetarian plan
is possible even within a single cuisine.

Conventions (see schemas.py):
- ingredient ids are lowercase snake_case and shared across recipes so they
  join cleanly against pantry state and the shopping list
- ingredient quantities are grams needed for one serving
- calories are per serving (one recipe == one day's dinner in the demo)
- cuisine is a single tag matching the fixed corpus tags exactly
"""

from schemas import Recipe

RECIPES: list[Recipe] = [
    # ---------------------------------------------------------------- italian
    Recipe(
        recipe_id="it_aglio_e_olio",
        title="Spaghetti Aglio e Olio",
        cuisine="italian",
        calories=520,
        vegetarian=True,
        ingredients={
            "spaghetti": 110,
            "olive_oil": 30,
            "garlic": 15,
            "red_pepper_flakes": 2,
            "parsley": 8,
        },
    ),
    Recipe(
        recipe_id="it_margherita_flatbread",
        title="Margherita Flatbread",
        cuisine="italian",
        calories=610,
        vegetarian=True,
        ingredients={
            "pizza_dough": 200,
            "tomato_sauce": 90,
            "mozzarella": 100,
            "basil": 6,
            "olive_oil": 12,
        },
    ),
    Recipe(
        recipe_id="it_penne_arrabbiata",
        title="Penne Arrabbiata",
        cuisine="italian",
        calories=540,
        vegetarian=True,
        ingredients={
            "penne": 110,
            "canned_tomatoes": 200,
            "garlic": 12,
            "red_pepper_flakes": 3,
            "olive_oil": 20,
            "parsley": 6,
        },
    ),
    Recipe(
        recipe_id="it_mushroom_risotto",
        title="Mushroom Risotto",
        cuisine="italian",
        calories=580,
        vegetarian=True,
        ingredients={
            "arborio_rice": 90,
            "mushroom": 150,
            "onion": 60,
            "parmesan": 30,
            "vegetable_broth": 400,
            "butter": 20,
            "white_wine": 40,
        },
    ),
    Recipe(
        recipe_id="it_caprese_farro_salad",
        title="Caprese Farro Salad",
        cuisine="italian",
        calories=470,
        vegetarian=True,
        ingredients={
            "farro": 80,
            "tomato": 120,
            "mozzarella": 80,
            "basil": 6,
            "olive_oil": 18,
            "balsamic_vinegar": 10,
        },
    ),
    Recipe(
        recipe_id="it_tuscan_white_bean_soup",
        title="Tuscan White Bean Soup",
        cuisine="italian",
        calories=430,
        vegetarian=True,
        ingredients={
            "cannellini_beans": 200,
            "kale": 80,
            "onion": 70,
            "garlic": 10,
            "carrot": 60,
            "vegetable_broth": 400,
            "olive_oil": 15,
        },
    ),
    Recipe(
        recipe_id="it_chicken_parmesan",
        title="Chicken Parmesan",
        cuisine="italian",
        calories=720,
        vegetarian=False,
        ingredients={
            "chicken_breast": 180,
            "breadcrumbs": 40,
            "egg": 50,
            "tomato_sauce": 120,
            "mozzarella": 60,
            "parmesan": 20,
            "olive_oil": 20,
        },
    ),
    Recipe(
        recipe_id="it_spaghetti_bolognese",
        title="Spaghetti Bolognese",
        cuisine="italian",
        calories=680,
        vegetarian=False,
        ingredients={
            "spaghetti": 110,
            "ground_beef": 150,
            "canned_tomatoes": 200,
            "onion": 60,
            "garlic": 10,
            "carrot": 50,
            "olive_oil": 15,
        },
    ),
    Recipe(
        recipe_id="it_shrimp_scampi_linguine",
        title="Shrimp Scampi Linguine",
        cuisine="italian",
        calories=590,
        vegetarian=False,
        ingredients={
            "linguine": 110,
            "shrimp": 140,
            "garlic": 15,
            "butter": 25,
            "white_wine": 50,
            "parsley": 6,
            "lemon": 30,
        },
    ),
    Recipe(
        recipe_id="it_prosciutto_arugula_pizza",
        title="Prosciutto and Arugula Pizza",
        cuisine="italian",
        calories=700,
        vegetarian=False,
        ingredients={
            "pizza_dough": 200,
            "mozzarella": 100,
            "prosciutto": 50,
            "arugula": 30,
            "olive_oil": 12,
            "parmesan": 15,
        },
    ),
    # --------------------------------------------------------------- american
    Recipe(
        recipe_id="am_grilled_cheese_tomato_soup",
        title="Grilled Cheese and Tomato Soup",
        cuisine="american",
        calories=560,
        vegetarian=True,
        ingredients={
            "bread": 90,
            "cheddar": 60,
            "butter": 20,
            "canned_tomatoes": 200,
            "onion": 50,
            "vegetable_broth": 250,
        },
    ),
    Recipe(
        recipe_id="am_mac_and_cheese",
        title="Baked Mac and Cheese",
        cuisine="american",
        calories=650,
        vegetarian=True,
        ingredients={
            "macaroni": 120,
            "cheddar": 90,
            "milk": 150,
            "butter": 20,
            "flour": 15,
            "breadcrumbs": 25,
        },
    ),
    Recipe(
        recipe_id="am_black_bean_burger",
        title="Black Bean Burger",
        cuisine="american",
        calories=540,
        vegetarian=True,
        ingredients={
            "black_beans": 160,
            "burger_bun": 80,
            "breadcrumbs": 30,
            "onion": 40,
            "corn": 50,
            "cheddar": 30,
        },
    ),
    Recipe(
        recipe_id="am_buffalo_cauliflower_bowl",
        title="Buffalo Cauliflower Bowl",
        cuisine="american",
        calories=480,
        vegetarian=True,
        ingredients={
            "cauliflower": 200,
            "hot_sauce": 30,
            "rice": 150,
            "black_beans": 100,
            "avocado": 60,
            "ranch_dressing": 25,
        },
    ),
    Recipe(
        recipe_id="am_loaded_baked_potato",
        title="Loaded Baked Potato",
        cuisine="american",
        calories=500,
        vegetarian=True,
        ingredients={
            "potato": 280,
            "cheddar": 50,
            "sour_cream": 40,
            "butter": 15,
            "broccoli": 80,
            "green_onion": 15,
        },
    ),
    Recipe(
        recipe_id="am_veggie_quesadilla",
        title="Veggie Quesadilla",
        cuisine="american",
        calories=520,
        vegetarian=True,
        ingredients={
            "tortilla": 100,
            "cheddar": 70,
            "bell_pepper": 70,
            "onion": 40,
            "corn": 50,
            "black_beans": 80,
        },
    ),
    Recipe(
        recipe_id="am_classic_cheeseburger",
        title="Classic Cheeseburger",
        cuisine="american",
        calories=700,
        vegetarian=False,
        ingredients={
            "ground_beef": 150,
            "burger_bun": 80,
            "cheddar": 40,
            "lettuce": 20,
            "tomato": 40,
            "onion": 30,
        },
    ),
    Recipe(
        recipe_id="am_bbq_pulled_chicken_sandwich",
        title="BBQ Pulled Chicken Sandwich",
        cuisine="american",
        calories=610,
        vegetarian=False,
        ingredients={
            "chicken_breast": 160,
            "bbq_sauce": 45,
            "burger_bun": 80,
            "coleslaw_mix": 60,
            "onion": 30,
        },
    ),
    Recipe(
        recipe_id="am_cobb_salad",
        title="Cobb Salad",
        cuisine="american",
        calories=560,
        vegetarian=False,
        ingredients={
            "romaine_lettuce": 120,
            "chicken_breast": 120,
            "bacon": 30,
            "egg": 50,
            "avocado": 60,
            "blue_cheese": 30,
            "tomato": 60,
        },
    ),
    Recipe(
        recipe_id="am_maple_glazed_salmon",
        title="Maple Glazed Salmon",
        cuisine="american",
        calories=590,
        vegetarian=False,
        ingredients={
            "salmon": 180,
            "maple_syrup": 25,
            "soy_sauce": 15,
            "broccoli": 120,
            "rice": 150,
            "garlic": 8,
        },
    ),
    # ---------------------------------------------------------------- chinese
    Recipe(
        recipe_id="cn_vegetable_fried_rice",
        title="Vegetable Fried Rice",
        cuisine="chinese",
        calories=480,
        vegetarian=True,
        ingredients={
            "rice": 180,
            "egg": 50,
            "peas": 50,
            "carrot": 50,
            "green_onion": 15,
            "soy_sauce": 20,
            "sesame_oil": 10,
        },
    ),
    Recipe(
        recipe_id="cn_kung_pao_tofu",
        title="Kung Pao Tofu",
        cuisine="chinese",
        calories=520,
        vegetarian=True,
        ingredients={
            "tofu": 200,
            "peanuts": 30,
            "bell_pepper": 70,
            "green_onion": 15,
            "soy_sauce": 20,
            "garlic": 10,
            "dried_chili": 3,
            "rice": 150,
        },
    ),
    Recipe(
        recipe_id="cn_mapo_tofu",
        title="Mapo Tofu",
        cuisine="chinese",
        calories=560,
        vegetarian=False,
        ingredients={
            "tofu": 220,
            "ground_pork": 90,
            "doubanjiang": 25,
            "green_onion": 15,
            "garlic": 10,
            "ginger": 8,
            "rice": 150,
            "sichuan_peppercorn": 2,
        },
    ),
    Recipe(
        recipe_id="cn_broccoli_garlic_stir_fry",
        title="Garlic Broccoli Stir Fry",
        cuisine="chinese",
        calories=410,
        vegetarian=True,
        ingredients={
            "broccoli": 200,
            "garlic": 15,
            "soy_sauce": 20,
            "sesame_oil": 10,
            "rice": 150,
            "ginger": 8,
        },
    ),
    Recipe(
        recipe_id="cn_egg_drop_noodle_soup",
        title="Egg Drop Noodle Soup",
        cuisine="chinese",
        calories=440,
        vegetarian=True,
        ingredients={
            "egg": 100,
            "vegetable_broth": 400,
            "green_onion": 15,
            "ginger": 8,
            "noodles": 90,
            "soy_sauce": 15,
        },
    ),
    Recipe(
        recipe_id="cn_kung_pao_chicken",
        title="Kung Pao Chicken",
        cuisine="chinese",
        calories=610,
        vegetarian=False,
        ingredients={
            "chicken_breast": 170,
            "peanuts": 30,
            "bell_pepper": 70,
            "green_onion": 15,
            "soy_sauce": 20,
            "dried_chili": 3,
            "garlic": 10,
            "rice": 150,
        },
    ),
    Recipe(
        recipe_id="cn_beef_and_broccoli",
        title="Beef and Broccoli",
        cuisine="chinese",
        calories=640,
        vegetarian=False,
        ingredients={
            "flank_steak": 170,
            "broccoli": 150,
            "soy_sauce": 25,
            "garlic": 10,
            "ginger": 8,
            "rice": 150,
            "oyster_sauce": 20,
        },
    ),
    Recipe(
        recipe_id="cn_sweet_and_sour_pork",
        title="Sweet and Sour Pork",
        cuisine="chinese",
        calories=680,
        vegetarian=False,
        ingredients={
            "pork": 170,
            "pineapple": 80,
            "bell_pepper": 70,
            "onion": 50,
            "ketchup": 40,
            "rice": 150,
            "cornstarch": 20,
        },
    ),
    Recipe(
        recipe_id="cn_shrimp_lo_mein",
        title="Shrimp Lo Mein",
        cuisine="chinese",
        calories=560,
        vegetarian=False,
        ingredients={
            "shrimp": 140,
            "lo_mein_noodles": 130,
            "cabbage": 80,
            "carrot": 50,
            "soy_sauce": 25,
            "sesame_oil": 10,
            "green_onion": 15,
        },
    ),
    Recipe(
        recipe_id="cn_general_tso_chicken",
        title="General Tso's Chicken",
        cuisine="chinese",
        calories=700,
        vegetarian=False,
        ingredients={
            "chicken_thigh": 180,
            "soy_sauce": 25,
            "hoisin_sauce": 30,
            "garlic": 10,
            "rice": 150,
            "broccoli": 80,
            "cornstarch": 20,
        },
    ),
    # ----------------------------------------------------------------- indian
    Recipe(
        recipe_id="in_chana_masala",
        title="Chana Masala",
        cuisine="indian",
        calories=520,
        vegetarian=True,
        ingredients={
            "chickpeas": 200,
            "onion": 70,
            "tomato": 120,
            "garlic": 10,
            "ginger": 8,
            "garam_masala": 6,
            "rice": 150,
        },
    ),
    Recipe(
        recipe_id="in_palak_paneer",
        title="Palak Paneer",
        cuisine="indian",
        calories=560,
        vegetarian=True,
        ingredients={
            "paneer": 150,
            "spinach": 200,
            "onion": 60,
            "tomato": 80,
            "garlic": 10,
            "ginger": 8,
            "garam_masala": 6,
        },
    ),
    Recipe(
        recipe_id="in_dal_tadka",
        title="Dal Tadka",
        cuisine="indian",
        calories=470,
        vegetarian=True,
        ingredients={
            "red_lentils": 150,
            "onion": 60,
            "tomato": 90,
            "garlic": 10,
            "cumin": 4,
            "turmeric": 3,
            "rice": 150,
        },
    ),
    Recipe(
        recipe_id="in_aloo_gobi",
        title="Aloo Gobi",
        cuisine="indian",
        calories=440,
        vegetarian=True,
        ingredients={
            "potato": 180,
            "cauliflower": 180,
            "onion": 60,
            "tomato": 80,
            "turmeric": 3,
            "cumin": 4,
            "peas": 50,
        },
    ),
    Recipe(
        recipe_id="in_vegetable_biryani",
        title="Vegetable Biryani",
        cuisine="indian",
        calories=590,
        vegetarian=True,
        ingredients={
            "basmati_rice": 180,
            "carrot": 60,
            "peas": 60,
            "onion": 70,
            "yogurt": 60,
            "garam_masala": 6,
            "cashews": 20,
        },
    ),
    Recipe(
        recipe_id="in_paneer_tikka_wrap",
        title="Paneer Tikka Wrap",
        cuisine="indian",
        calories=540,
        vegetarian=True,
        ingredients={
            "paneer": 140,
            "tortilla": 90,
            "yogurt": 50,
            "onion": 50,
            "bell_pepper": 60,
            "garam_masala": 5,
        },
    ),
    Recipe(
        recipe_id="in_chicken_tikka_masala",
        title="Chicken Tikka Masala",
        cuisine="indian",
        calories=650,
        vegetarian=False,
        ingredients={
            "chicken_breast": 180,
            "yogurt": 60,
            "tomato": 120,
            "onion": 70,
            "garlic": 10,
            "ginger": 8,
            "garam_masala": 6,
            "rice": 150,
        },
    ),
    Recipe(
        recipe_id="in_butter_chicken",
        title="Butter Chicken",
        cuisine="indian",
        calories=720,
        vegetarian=False,
        ingredients={
            "chicken_thigh": 180,
            "butter": 25,
            "tomato": 120,
            "cream": 50,
            "onion": 60,
            "garam_masala": 6,
            "rice": 150,
        },
    ),
    Recipe(
        recipe_id="in_lamb_rogan_josh",
        title="Lamb Rogan Josh",
        cuisine="indian",
        calories=690,
        vegetarian=False,
        ingredients={
            "lamb": 180,
            "yogurt": 60,
            "onion": 70,
            "tomato": 100,
            "garlic": 10,
            "ginger": 8,
            "garam_masala": 7,
            "rice": 150,
        },
    ),
    Recipe(
        recipe_id="in_fish_curry",
        title="South Indian Fish Curry",
        cuisine="indian",
        calories=560,
        vegetarian=False,
        ingredients={
            "white_fish": 180,
            "coconut_milk": 120,
            "onion": 60,
            "tomato": 90,
            "turmeric": 3,
            "curry_leaves": 2,
            "rice": 150,
        },
    ),
]
